version: '3.7'
services:
    postgres:
        image: postgres:10-alpine
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "/db-data:/var/lib/postgresql/data"

    local-runner:
        image: amazon/mwaa-local:2_5
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - "/mnt/c/ot-datateam-airflow/dags:/usr/local/airflow/dags"
            - "/mnt/c/ot-datateam-airflow/plugins:/usr/local/airflow/plugins"
            - "/mnt/c/ot-datateam-airflow/requirements/requirements.txt:/usr/local/airflow/requirements"
            - "/mnt/c/ot-datateam-airflow/startup/startup_script:/usr/local/airflow/startup"
        ports:
            - "8080:8080"
        command: local-runner
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        env_file:
            - ./config/.env.localrunner
